function EventHandler(menu, gD) {
  this.menu = menu;
  this.gD = gD;

}

const Events = {
  COLLECT_HYPE: "COLLECT_HYPE",
  COLLECT_1000_HYPE: "COLLECT_1000_HYPE",
  COLLECT_TREASURE: "COLLECT_TREASURE",
  COLLECT_GOLDEN_SHAMROCK: "COLLECT_GOLDEN_SHAMROCK",
  DO_JUMP: "DO_JUMP",
  DO_DOUBLE_JUMP: "DO_DOUBLE_JUMP",
  USE_STOPWATCH: "USE_STOPWATCH",
  USE_FIVE_STARS: "USE_FIVE_STARS",
  USE_FEATHER: "USE_FEATHER",
  USE_TREASURE: "USE_TREASURE",
  USE_MAGNET: "USE_MAGNET",
  USE_ROCKET: "USE_ROCKET",
  USE_ALL_ITEMS_AT_ONCE: "USE_ALL_ITEMS_AT_ONCE",
  JUMP_OUT_OF_BOUNDS: "JUMP_OUT_OF_BOUNDS",
  STAR_BEFORE_LAVA: "STAR_BEFORE_LAVA",
  DEATH: "DEATH",
  END_OF_ROUND_TOTAL_SLOWED_TIME: "END_OF_ROUND_TOTAL_SLOWED_TIME",
  END_OF_ROUND_TOTAL_TRAVELLED_DISTANCE: "END_OF_ROUND_TOTAL_TRAVELLED_DISTANCE",
  END_OF_ROUND_TOTAL_REVERSE_DISTANCE: "END_OF_ROUND_TOTAL_REVERSE_DISTANCE",
  SET_OWNED_HYPE: "SET_OWNED_HYPE",
  LVL_ITEM: "LVL_ITEM",
  LVL_ITEM_MAX: "LVL_ITEM_MAX",
  TIME_PLAYED: "TIME_PLAYED"
}